### ISSUE TITLE
Using --belts or -b causes crashes and the graph's rates are misaligned

### ISSUE THREAD

**Issue by gamingdoom** [IceMoonMagic/Satisfactory-Splitter-Calculator#1]
# ``--belts`` issue:
- Input (this does the same thing with cli.py and api.py):
    ``python api.py 225 15 --belts 60 120``
- Output:
  ```
  Traceback (most recent call last):
    File "/home/user/Satisfactory-Splitter-Calculator/api.py", line 60, in <module>
      main()
    File "/home/user/Satisfactory-Splitter-Calculator/api.py", line 43, in main
      cn.smart_ratio(*args.into, mk=args.mk, alt_belts=args.belts))
    File "/home/user/Satisfactory-Splitter-Calculator/conveyor_nodes.py", line 391, in smart_ratio
      _smart_ratio(list(targets), 0, best_splits, 0)
    File "/home/user/Satisfactory-Splitter-Calculator/conveyor_nodes.py", line 357, in _smart_ratio
      for belt in belts:
  ```
# ``-b`` issue
- Input:
    ``python cli.py 225 15 -b 2``
- Output:
    ```
      Traceback (most recent call last):
      File "/home/pranay/Satisfactory-Splitter-Calculator/cli.py", line 269, in <module>
        main_cli()
      File "/home/pranay/Satisfactory-Splitter-Calculator/cli.py", line 244, in main_cli
        main(*args.into, name=args.to_file, **foo)
      File "/home/pranay/Satisfactory-Splitter-Calculator/cli.py", line 137, in main
        cn.smart_ratio(*num, mk=mk, alt_belts=belts))
      File "/home/pranay/Satisfactory-Splitter-Calculator/conveyor_nodes.py", line 340, in smart_ratio
        belts = alt_belts.sort() if alt_belts else [60, 120, 270, 480, 780][:mk]
    TypeError: slice indices must be integers or None or have an __index__ method
    ```
# Graph issue
- Input:
    ``python cli.py 225 15``
- [Output](https://github.com/IceMoonMagic/Satisfactory-Splitter-Calculator/files/7716543/splitters.gv.pdf)

**Comment by IceMoonMagic** [comment]
### `--belts`
So, I'm pretty sure I noticed that a little after my the last push when using it myself. I then fixed it and forgot to push it to GitHub... So it should be fixed now.

### `-b`
That was from the argument parser creating a list of a single int instead of just giving the int. I thought I corrected that somewhere before, but I guess it was in one of the other files' parser and I didn't check for that elsewhere. (Fixed)

### Graph
I don't actually see anything wrong with the provided output, besides not being the easiest thing to follow (which I can't do much about). 
The two outputs are 225 and 15 with a total input of 240, so that seems fine. The smart splitter is taking out a full 60 and sends the remaining elsewhere. The normal splitters and mergers seem to be correct.

The only things I can see that may be off issue are 1) difficulty noticing that the splitter getting 180 is going has three outputs, and 2) the second merger has 4 inputs which isn't possible in-game. 
(1) I can't do much about, maybe consider trying different line types or line engines, or something besides Graphviz. (2) Something I'm considering but I need to make sure it groups nodes together that are somewhat near to each other or it will become an even bigger mess.
